spring.application.name=requestmngr
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8081}
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
app.initial-admin.username=${APP_INITIAL_ADMIN_USERNAME:}
app.initial-admin.password=${APP_INITIAL_ADMIN_PASSWORD:}
app.initial-admin.display-name=${APP_INITIAL_ADMIN_DISPLAY_NAME:}
