CREATE TABLE purchase_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_number VARCHAR(50) NOT NULL,
    department VARCHAR(120) NOT NULL,
    requester_name VARCHAR(150) NOT NULL,
    requested_on DATE NOT NULL,
    purchase_reason TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL,
    buyer_name VARCHAR(150),
    manager_name VARCHAR(150),
    cost_center VARCHAR(80),
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_purchase_requests_request_number UNIQUE (request_number),
    CONSTRAINT ck_purchase_requests_priority
        CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    CONSTRAINT ck_purchase_requests_status
        CHECK (status IN (
            'OPEN',
            'PENDING_APPROVAL',
            'APPROVED',
            'IN_PURCHASE',
            'PARTIALLY_RECEIVED',
            'COMPLETED',
            'CANCELLED'
        ))
);

CREATE TABLE purchase_request_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_request_id BIGINT NOT NULL,
    description VARCHAR(500) NOT NULL,
    brand_model VARCHAR(250),
    quantity INTEGER NOT NULL,
    supplier_name VARCHAR(200),
    total_value NUMERIC(14, 2) NOT NULL,
    received_on DATE,
    checked_by VARCHAR(150),
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase_request_items_purchase_request
        FOREIGN KEY (purchase_request_id)
        REFERENCES purchase_requests (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_purchase_request_items_quantity
        CHECK (quantity > 0),
    CONSTRAINT ck_purchase_request_items_total_value
        CHECK (total_value >= 0),
    CONSTRAINT ck_purchase_request_items_status
        CHECK (status IN ('PENDING', 'PURCHASED', 'RECEIVED', 'CANCELLED')),
    CONSTRAINT ck_purchase_request_items_received_on
        CHECK (status <> 'RECEIVED' OR received_on IS NOT NULL)
);

CREATE INDEX idx_purchase_requests_status ON purchase_requests (status);
CREATE INDEX idx_purchase_requests_department ON purchase_requests (department);
CREATE INDEX idx_purchase_requests_requester_name ON purchase_requests (requester_name);
CREATE INDEX idx_purchase_requests_requested_on ON purchase_requests (requested_on DESC);
CREATE INDEX idx_purchase_request_items_purchase_request_id
    ON purchase_request_items (purchase_request_id);
